# Puerto de la aplicación
server.port=8081

# Conexión a MySQL 
spring.datasource.url=jdbc:mysql://localhost:3306/catalogo_juegos?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Magnus20

# JPA / Hibernate Config
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.defer-datasource-initialization=true

# Formatear el SQL en consola para que sea legible
spring.jpa.properties.hibernate.format_sql=true
spring.sql.init.mode=always

# Configuración de Logs para ver las consultas a la base de datos
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# Evitar el aviso de "open-in-view" en la consola
spring.jpa.open-in-view=false

# ¡ESTA LÍNEA ES VITAL PARA EL DISEÑO!
spring.web.resources.static-locations=classpath:/static/